# Generated by Django 3.2.4 on 2021-07-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_room_contactno'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='room',
            field=models.ManyToManyField(to='manager.Room'),
        ),
    ]
