# Generated by Django 3.2.4 on 2021-07-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='', max_length=40)),
                ('lastname', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
