# Generated by Django 3.2.4 on 2021-07-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacationtrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=40)),
                ('lname', models.CharField(default='', max_length=40)),
                ('age', models.IntegerField(default=0)),
                ('country', models.CharField(default='', max_length=40)),
                ('contactno', models.IntegerField(default=0)),
                ('package', models.IntegerField(blank=True, null=True)),
                ('no_of_days', models.IntegerField(default=0)),
            ],
        ),
    ]
