# Generated by Django 3.2.4 on 2021-07-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0002_auto_20210706_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacationtrip',
            name='documents',
            field=models.FileField(default='/vacation/default.pdf', upload_to='vacation/documents/'),
        ),
        migrations.AddField(
            model_name='vacationtrip',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
