# Generated by Django 3.2.4 on 2021-07-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacation', '0003_auto_20210708_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacationtrip',
            name='documents',
            field=models.FileField(default='dummy.pdf', upload_to='documents/'),
        ),
    ]
