# Generated by Django 3.2.4 on 2021-07-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realestatecolmn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('house_age', models.FloatField(default=0)),
                ('MRT_station', models.FloatField(default=0)),
                ('con_stores', models.IntegerField(default=0)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(default=0)),
                ('predicted', models.FloatField(default=0)),
            ],
        ),
    ]
