# Generated by Django 3.2.4 on 2021-07-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrer', models.CharField(choices=[('Programmer', 'Programmer'), ('Teacher', 'Teacher'), ('Businessman', 'Businessman'), ('Farmer', 'Farmer'), ('Doctor', 'Doctor')], default='Businessman', max_length=20)),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('state', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('desc', models.TextField()),
                ('salary', models.FloatField()),
                ('is_verify', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('Student_class', models.IntegerField(default=1)),
                ('rollno', models.IntegerField(blank=True, null=True)),
                ('is_verify', models.BooleanField(default=False)),
            ],
        ),
    ]
