# Generated by Django 3.2.4 on 2021-06-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210630_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='school',
        ),
        migrations.RemoveField(
            model_name='education',
            name='school_certificate',
        ),
    ]
