# Generated by Django 3.2.4 on 2021-06-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210630_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='college',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='highschool',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='school',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='schoolfile',
        ),
        migrations.RemoveField(
            model_name='education',
            name='college',
        ),
        migrations.RemoveField(
            model_name='education',
            name='college_certificate',
        ),
        migrations.RemoveField(
            model_name='education',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='education',
            name='highschool',
        ),
        migrations.RemoveField(
            model_name='education',
            name='highschool_certificate',
        ),
        migrations.RemoveField(
            model_name='education',
            name='last_name',
        ),
    ]
