# Generated by Django 3.2.4 on 2021-06-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210630_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='company',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='designation',
            name='dateofjoining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='desg_name',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='designation',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='designation',
            name='firstname',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='designation',
            name='lastname',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='designation',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='designation',
            name='role',
            field=models.CharField(default='', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='education',
            name='college',
            field=models.CharField(default='', editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='education',
            name='college_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='education',
            name='first_name',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='highschool',
            field=models.CharField(default='', editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='education',
            name='highschool_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='education',
            name='last_name',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='school',
            field=models.CharField(default='', editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='education',
            name='school_certificate',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
