# Generated by Django 3.2.4 on 2021-07-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='contactno',
            field=models.IntegerField(default=0),
        ),
    ]
