# Generated by Django 3.2.4 on 2021-07-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garmnentscolmn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Saturday', '1'), ('Sunday', '2'), ('Monday', '3'), ('Tuesday', '4'), ('Wednesday', '5'), ('Thursday', '6')], default='Saturday', max_length=10)),
                ('team', models.IntegerField(default=0)),
                ('targeted_productivity', models.FloatField(default=0)),
                ('over_time', models.IntegerField(default=0)),
                ('incentive', models.IntegerField(blank=True, null=True)),
                ('idle_time', models.IntegerField(unique=True)),
                ('idle_men', models.IntegerField(default=0)),
                ('no_of_style_change', models.IntegerField(default=0)),
                ('no_of_workers', models.IntegerField(default=0)),
            ],
        ),
    ]
