# Generated by Django 3.2.4 on 2021-07-05 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_alter_garmnentscolmn_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garmnentscolmn',
            name='day',
            field=models.CharField(choices=[('1', 'Saturday'), ('2', 'Sunday'), ('3', 'Monday'), ('4', 'Tuesday'), ('5', 'Wednesday'), ('6', 'Thursday')], default='Saturday', max_length=20),
        ),
    ]
