# Generated by Django 3.2.4 on 2021-07-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_alter_garmnentscolmn_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='garmnentscolmn',
            name='person',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
