# Generated by Django 3.2.4 on 2021-07-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0004_garmnentscolmn_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garmnentscolmn',
            old_name='person',
            new_name='username',
        ),
        migrations.AddField(
            model_name='garmnentscolmn',
            name='predicted',
            field=models.CharField(choices=[('Medium productivity', 'Medium productivity'), ('High productivity', 'High productivity')], default=1, max_length=40),
            preserve_default=False,
        ),
    ]
